version: '3.9'

services:

    database:
        image: mysql:8
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASS}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
            - MYSQL_DATABASE=${DB_NAME}
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql

    api:
        build: .
        ports:
            - "${PORT}:${PORT}"
        depends_on:
            - database
        env_file:
            - .env
    
volumes:
    dbdata:
